### ISSUE TITLE
Error: Evaluation failed: Object

### ISSUE THREAD

**Issue by junhoyeo** [junhoyeo/honeycomb#5]
```
Error: Evaluation failed: Object
    at ExecutionContext._evaluateInternal (/Users/junhoyeo/honeycomb/node_modul)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/Users/junhoyeo/honeycomb/node_modules/)
    at async solveProblems (/Users/junhoyeo/honeycomb/index.js:65:26)
    at async /Users/junhoyeo/honeycomb/index.js:149:9
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/junhoyeo/honeycomb/node_modules/pup)
    at DOMWorld.evaluate (/Users/junhoyeo/honeycomb/node_modules/puppeteer/lib/)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/junhoyeo/honeycomb/node_modules/puppeteer/lib/)
    at Page.evaluate (/Users/junhoyeo/honeycomb/node_modules/puppeteer/lib/Page)
    at Page.<anonymous> (/Users/junhoyeo/honeycomb/node_modules/puppeteer/lib/h)
    at solveProblems (/Users/junhoyeo/honeycomb/index.js:65:37)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/junhoyeo/honeycomb/index.js:149:9
```
일정 확률로, 특히 인터넷 연결 상태가 안 좋을 때 위와 같은 에러가 발생합니다.

**Comment by rycont** [comment]
how about modify waitUntil property to networkidle0 or networkidle2?

**Comment by junhoyeo** [comment]
@rycont You are just pure genius,, I'll check that soon, or you may contribute and PR 🙌

**Comment by rycont** [comment]
Did it worked..?

**Comment by junhoyeo** [comment]
> was it worked..?

No, I didn't tried it yet. Sorry 😥
